const level1 = new Level(
    [    
        new BackgroundObject('img/background/game_background_2/layers/sky.png', -1 * 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/rocks.png', -1 * 779, 0),    
        new BackgroundObject('img/background/game_background_2/layers/ground.png', -1 * 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/sky.png', 0, 0),
        new BackgroundObject('img/background/game_background_2/layers/rocks.png', 0, 0),    
        new BackgroundObject('img/background/game_background_2/layers/ground.png', 0, 0),
        new BackgroundObject('img/background/game_background_2/layers/sky.png', 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/rocks.png', 779, 0),    
        new BackgroundObject('img/background/game_background_2/layers/ground.png', 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/sky.png', 2 * 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/rocks.png', 2 * 779, 0),    
        new BackgroundObject('img/background/game_background_2/layers/ground.png', 2 * 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/sky.png', 3 * 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/rocks.png', 3 * 779, 0),    
        new BackgroundObject('img/background/game_background_2/layers/ground.png', 3 * 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/sky.png', 4 * 779, 0),
        new BackgroundObject('img/background/game_background_2/layers/rocks.png', 4 * 779, 0),    
        new BackgroundObject('img/background/game_background_2/layers/ground.png', 4 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/sky.png', -1 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/clouds_1.png', -1 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_1.png', -1 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_2.png', -1 * 779, 0),    
        // new BackgroundObject('img/background/game_background_1/layers/sky.png', 0, 0),
        // new BackgroundObject('img/background/game_background_1/layers/clouds_1.png', 0, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_1.png', 0, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_2.png', 0, 0),    
        // new BackgroundObject('img/background/game_background_1/layers/sky.png', 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/clouds_1.png', 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_1.png', 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_2.png', 779, 0),    
        // new BackgroundObject('img/background/game_background_1/layers/sky.png', 2 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/clouds_1.png', 2 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_1.png', 2 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_2.png', 2 * 779, 0),    
        // new BackgroundObject('img/background/game_background_1/layers/sky.png', 3 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/clouds_1.png', 3 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_1.png', 3 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_2.png', 3 * 779, 0),    
        // new BackgroundObject('img/background/game_background_1/layers/sky.png', 4 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/clouds_1.png', 4 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_1.png', 4 * 779, 0),
        // new BackgroundObject('img/background/game_background_1/layers/rocks_2.png', 4 * 779, 0),    
    ],
    [
        new Cloud('img/background/game_background_2/layers/clouds_1.png', 300, 0),
        new Cloud('img/background/game_background_2/layers/clouds_2.png', 700, 0),
        new Cloud('img/background/game_background_2/layers/clouds_2.png', 950, 0),
        new Cloud('img/background/game_background_2/layers/clouds_1.png', 1300, 0),
        new Cloud('img/background/game_background_2/layers/clouds_1.png', 1600, 0),
        new Cloud('img/background/game_background_2/layers/clouds_2.png', 2000, 0),
        new Cloud('img/background/game_background_2/layers/clouds_2.png', 2450, 0),
        new Cloud('img/background/game_background_2/layers/clouds_1.png', 2700, 0),
        new Cloud('img/background/game_background_2/layers/clouds_1.png', 3000, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_2.png', 300, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_3.png', 700, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_4.png', 950, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_2.png', 1300, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_3.png', 1600, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_4.png', 2000, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_2.png', 2450, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_3.png', 2700, 0),
        // new Cloud('img/background/game_background_1/layers/clouds_4.png', 3000, 0),
    ],
    [
        
    ],
    [
        
    ],
    [
        new Dagger('img/daggers/PNG/dagger.png', 100, 0),
        new Dagger('img/daggers/PNG/dagger.png', 400, 0),
        new Dagger('img/daggers/PNG/dagger.png', 750, 0),
        new Dagger('img/daggers/PNG/dagger.png', 950, 0),
        new Dagger('img/daggers/PNG/dagger.png', 1100, 0),
        new Dagger('img/daggers/PNG/dagger.png', 1300, 0),
        new Dagger('img/daggers/PNG/dagger.png', 1450, 0),
        new Dagger('img/daggers/PNG/dagger.png', 1700, 0),
        new Dagger('img/daggers/PNG/dagger.png', 1900, 0),
        new Dagger('img/daggers/PNG/dagger.png', 2200, 0),
        new Dagger('img/daggers/PNG/dagger.png', 2350, 0),
    ],
    [
        
    ],

    );